### ISSUE TITLE
功能请求：默认标签

### ISSUE THREAD

**Issue by KYLN24** [fduhole/vue#10]
不添加自定义标签时，自动添加“默认”标签

**Comment by KYLN24** [comment]
优化标签添加（在iOS上表现得极其离谱，其他设备不知道）

**Comment by hasbai** [comment]
> 不添加自定义标签时，自动添加“默认”标签

已完成 [文档](https://www.showdoc.com.cn/1346921193013996?page_id=6682733452567346)

**Comment by KYLN24** [comment]
前端已适配
