### ISSUE TITLE
[BUG] 网页端需要两次才能登录进去

### ISSUE THREAD

**Issue by hasbai** [fduhole/vue#13]
复现步骤：

1. 登出账号
2. 输入用户名密码登录

问题描述：
第一次登录后发现 POST 请求为 canceled 状态，需要再次点击登录才能登录成功

**Comment by KYLN24** [comment]
我觉得这是后端的锅👀

**Comment by hasbai** [comment]
我觉得不是，直接发包调试是正常的
![屏幕截图 2021-04-29 161628](https://user-images.githubusercontent.com/34417826/116521241-4bb54180-a906-11eb-8545-8cbe869db753.jpg)

**Comment by KYLN24** [comment]
已解决
