### ISSUE TITLE
iPad上无法滚动页面

### ISSUE THREAD

**Issue by KYLN24** [fduhole/vue#25]
系统：iPadOS 15.1
设备：iPad Air 第三代

**Comment by dest1n1s** [comment]
已知悉。目前已知iPad与MatePad均会发生上述问题，而Android手机暂未发生该现象。iPhone与Mac OS上的情况待测试。

另外，树洞相关的issue之后请发在OpenTreeHole/vue中。

**Comment by dest1n1s** [comment]
经测试，Mac OS上的Safari未发现问题。

**Comment by dest1n1s** [comment]
将页面滚动用OverlayScrollbar实现后，iPad上依然会存在滚动问题（推测是因为滚动手势与Safari自带其他手势，如拖动页面、隐藏地址栏冲突）。在找到更好的解决方案之前Safari浏览器会被视作普通窄屏设备处理（即显示单栏）。
